version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            python3 -m venv /usr/local/share/virtualenvs/tap-google-sheets
            source /usr/local/share/virtualenvs/tap-google-sheets/bin/activate
            pip install .[test]
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-google-sheets/bin/activate
            pylint tap_google_sheets -d C,R,W
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_google_sheets/schemas/*.json
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-google-sheets/bin/activate
            pip install nose2 parameterized nose2[coverage_plugin]>=0.6.5
            nose2 --with-coverage -v -s tests/unittests
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      - run:
          name: 'Integration Tests'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            mkdir /tmp/${CIRCLE_PROJECT_REPONAME}
            export STITCH_CONFIG_DIR=/tmp/${CIRCLE_PROJECT_REPONAME}
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap=tap-google-sheets tests
      - slack/notify-on-failure:
          only_for_branches: master
      - store_artifacts:
          path: /tmp/tap-google-sheets

workflows:
  version: 2
  commit: &commit_jobs
    jobs:
      - build:
          context:
            - circleci-user
            - tier-1-tap-user
  build_daily:
    <<: *commit_jobs
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
