version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-v4
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            virtualenv -p python3 ~/.virtualenvs/tap-google-sheets
            source ~/.virtualenvs/tap-google-sheets/bin/activate
            pip install .[dev]
            pylint tap_google_sheets -d C,R,W
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json ~/.virtualenvs/tap-google-sheets/lib/python3.8/site-packages/tap_google_sheets/schemas/*.json
      - add_ssh_keys
      - run:
          name: 'Integration Tests'
          command: |
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/sandbox dev_env.sh
            source dev_env.sh
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            run-test --tap=tap-google-sheets \
                     --target=target-stitch \
                     --orchestrator=stitch-orchestrator \
                     --email=harrison+sandboxtest@stitchdata.com \
                     --password=$SANDBOX_PASSWORD \
                     --client-id=50 \
                     tests/tap_combined_test.py
      - slack/notify-on-failure:
          only_for_branches: master

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
